version: "3"
services:
  appserver:
    container_name: server-risephonebook
    image: alpha110r/server-risephonebook:alon-001
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    privileged: true

